# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='year',
        ),
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
